### ISSUE TITLE
Не указано в чем измеряется цена.

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#10]
1. В приложении менеджера заходим в панель блюд. Не указано в чем измеряется стоимость блюд.
![image](https://user-images.githubusercontent.com/71391450/102413881-ae1c3e00-4006-11eb-8181-2f0d8067dccf.png)
2. Ожидаемое поведение - указывается в какой валюте указана стоимость блюд.

**Comment by MrDokara** [comment]
Исправлено 
![image](https://user-images.githubusercontent.com/66333824/102463817-a6878400-405c-11eb-9bff-27b43e0bdbf9.png)
