### ISSUE TITLE
Вылет программы менеджера 1

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#11]
1. В приложении менеджера заходим в панель блюд. Заходим в меню для изменения блюда. При смене цены на 0 происходит некорректный выход из программы, что влечет за собой потерю информации о блюде, которое подверглось изменению. 
![image](https://user-images.githubusercontent.com/71391450/102414365-7661c600-4007-11eb-91f6-81e4a9d1c881.png)
2. Ожидаемое поведение - Невозможность установить цену = 0.

**Comment by User1Root** [comment]
Так умер харчок умер.

**Comment by bilskla** [comment]
![vvFfVAjoub4peA8-sL30Mg](https://user-images.githubusercontent.com/71009109/102451389-6d91e400-4049-11eb-8791-af7ca84663ba.jpeg)

**Comment by MrDokara** [comment]
Исправлено
![image](https://user-images.githubusercontent.com/66333824/102463977-d59df580-405c-11eb-85c9-7c1cab1e469d.png)
![image](https://user-images.githubusercontent.com/66333824/102464057-f36b5a80-405c-11eb-8690-507582387446.png)
