### ISSUE TITLE
Вылет программы менеджера 2

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#12]
1. В приложении менеджера заходим в панель блюд. Заходим в меню для изменений блюда. При смене цены на любой текст при помощи вставки ctrl+v, происходит некорректный выход из программы, что влечет за собой потерю информации о блюде, которое подверглось изменению.
![image](https://user-images.githubusercontent.com/71391450/102414732-1586bd80-4008-11eb-9cbb-7fcb6951d4a7.png)
2. Ожидаемое поведение - Невозможность установить цену равную скопированной строке.

**Comment by User1Root** [comment]
Так умер juice.

**Comment by MrDokara** [comment]
Исправлено
![image](https://user-images.githubusercontent.com/66333824/102464132-08e08480-405d-11eb-988f-6c66ac6007d9.png)
