### ISSUE TITLE
Смена пароля официанта 1

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#13]
1. В приложении менеджера заходим в панель изменение аккаунта официанта. Есть возможность установить пароль, содержащий в себе 0, хотя в приложении для официантов нет возможности ввести 0 при авторизации.
![image](https://user-images.githubusercontent.com/71391450/102415262-ef155200-4008-11eb-8c15-0ed44e9c7d9f.png)
2. Ожидаемый результат - в приложении для официантов есть возможность ввести 0 при авторизации.

**Comment by MrDokara** [comment]
Исправлено
