### ISSUE TITLE
Смена пароля официанта 2

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#14]
1. В приложении менеджера заходим в панель изменение аккаунта официанта. Есть возможность установить пароль, на любой текст при помощи вставки ctrl + v, хотя в приложении официанта при авторизации есть возможность вводить только цифры от 1 до 9.
![image](https://user-images.githubusercontent.com/71391450/102415504-57643380-4009-11eb-87ed-73782ede03e9.png)
2. Ожидаемое поведение - невозможность установить пароль через ctrl + v.

**Comment by MrDokara** [comment]
Исправлено
