### ISSUE TITLE
Не логичный чек в приложении официанта

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#18]
1. В приложении официанта при выдаче чека, указывается вычисление итоговой стоимости не по начальной цене за порцию блюда, а уже по итоговой общей стоимости, а также не указано в чем измеряется итоговая стоимость заказа.
![image](https://user-images.githubusercontent.com/71391450/102417481-d6a73680-400c-11eb-9521-60b4fe1c8ee4.png)
2. Ожидаемое поведение - присутствует логика в постарении чека.

**Comment by sA1mon** [comment]
Фихед
