### ISSUE TITLE
Отсутствие корректной навигации по приложению официанта 

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#19]
1. В приложении официанта при выборе 1 из категорий блюд, отсутствует возможность вернуться назад к общему меню с категориями блюд.
![image](https://user-images.githubusercontent.com/71391450/102417839-9a280a80-400d-11eb-86a1-0ef9417c4cfc.png)
2. Ожидаемое поведение - корректная навигация по приложению официанта.

**Comment by sA1mon** [comment]
Чтобы вернуться к предыдущему пункту, нужно нажать ПКМ в любой рабочей области.
