### ISSUE TITLE
Некорректное отображение в приложении официанта

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#20]
1. В приложении официанта, если набрать много заказов, то при просмотре заказов происходит их некорректное отображение.
![image](https://user-images.githubusercontent.com/71391450/102418165-40741000-400e-11eb-986a-c48476bb2516.png)
2. Ожидаемое поведение - корректное отображение заказов.

**Comment by sA1mon** [comment]
Скролл скрыт, можно скроллить колесиком, отображение соответствует заявленному.
