### ISSUE TITLE
Некорректное отображение в приложении повара

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#21]
1. В приложении повара, если набрать много заказов в приложении официанта, то при просмотре заказов со стороны повара происходит их некорректное отображение.
![image](https://user-images.githubusercontent.com/71391450/102418332-92b53100-400e-11eb-905a-1cf2fa301001.png)
2. Ожидаемое поведение - корректное отображение заказов.

**Comment by sA1mon** [comment]
Скролл скрыт, можно скроллить колесиком, отображение соответствует заявленному.
