### ISSUE TITLE
Некорректное отображение контента на сайте

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#22]
1. На сайте во вкладке About us, если спуститься в самый низ страницы не отображаются должности персонала.
![image](https://user-images.githubusercontent.com/71391450/102418574-0c4d1f00-400f-11eb-8eb9-6e237379342d.png)
2. Ожидаемое поведение - корректное отображение контента.

**Comment by bilskla** [comment]
Исправлено, теперь контент отображается корректно.
Тема закрыта
