### ISSUE TITLE
Неудобное выпадающее меню на сайте

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#23]
1. На сайте, если навести на логин, выпадает меню, на которое трудно перейти, так как если переходить медленно, оно пропадает. 
![image](https://user-images.githubusercontent.com/71391450/102418795-841b4980-400f-11eb-8c9c-d7d11439f8c7.png)
2. Ожидаемое поведение - удобное выпадающее меню.

**Comment by bilskla** [comment]
К сожалению, функции задержки в JS пока что нет (и не факт, что будет), а народными методами исправить данную ошибку не получается. Будем считать, что это тест на реакцию клиента :)
