### ISSUE TITLE
Ошибка сервера на сайте

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#24]
1. На сайте, на странице корзины, при нажатии на кнопку "Go to checkout" выкидывается исключение.
![image](https://user-images.githubusercontent.com/71391450/102419209-64d0ec00-4010-11eb-8eed-a9a3bd08b849.png)
2. Ожидаемое поведение - отсутствие ошибок при нажатии на кнопку "Go to checkout".

**Comment by bilskla** [comment]
Исправлено (подчищены следы, оставшиеся от службы подтверждения номера телефона)
Тема закрыта
