### ISSUE TITLE
❗❗❗ ВНИМАНИЕ АКЦИЯ ❗❗❗

### ISSUE THREAD

**Issue by sA1mon** [MrDokara/restaurant-system#7]
![image](https://user-images.githubusercontent.com/24940589/102330899-2d742800-3f9b-11eb-87e2-4441762f5a18.png)
ТОЛЬКО СЕГОДНЯ ПО ПРОМОКОДУ **ANDREYLOH** 100$ НА ДЕПОЗИТ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bilskla** [comment]
Семен дурачок.
Тема закрыта
