### ISSUE TITLE
Несогласование русского и английского языка в приложении менеджера.

### ISSUE THREAD

**Issue by qbk3** [MrDokara/restaurant-system#9]
1. В приложении менеджера заходим в панель блюд. Наблюдается что все меню написано на английском языке, хотя весь интерфейс на русском.
![image](https://user-images.githubusercontent.com/71391450/102413490-10287380-4006-11eb-916f-570d6e6a56b1.png)
2. Ожидаемое поведение - согласованность языков в приложении.

**Comment by bilskla** [comment]
Принято. Русифицирую контент базы данных и контент на сайте

**Comment by bilskla** [comment]
Русификация закончена.
Тема закрыта
